### ISSUE TITLE
Error de ESLint

### ISSUE THREAD

**Issue by emrivero** [sigcorporativo-ja/mapea-create-plugin#1]
Nada mas iniciar la herramienta en modo desarrollo aparece el mismo mensaje de error varias veces.
![Captura de pantalla de 2019-09-13 13-06-48](https://user-images.githubusercontent.com/30650412/64858640-3bb0f700-d628-11e9-8af5-23d08cdf0b91.png)

**Comment by jgleal** [comment]
es un problema derivado de windows-linux. eslint lo corrige automáticamente con -fix, pero aún así se ha eliminado dicha regla
