### ISSUE TITLE
Error al hacer npm run build

### ISSUE THREAD

**Issue by emrivero** [sigcorporativo-ja/mapea-create-plugin#2]
Esto no es tanto un problema de ESLint sino un error en el script de generación del entry-point.
![Captura de pantalla de 2019-09-13 13-51-22](https://user-images.githubusercontent.com/30650412/64860522-b4ff1880-d62d-11e9-970c-a43304f9d5ba.png)

**Comment by jgleal** [comment]
se ha solucionado por un lado usando slash para simplificar el entry point, y por otro relajando eslint para que sea menos exhaustivo
